// Bal Jyoti Foundation - Events Database
window.BAL_JYOTI_EVENTS = [
  {
    id: 1,
    title: "Bamboo Craft Workshop",
    category: "Crafts",
    subCategories: ["Workshops", "Crafts"],
    status: "Upcoming",
    date: "2026-08-10",
    startTime: "10:00",
    endTime: "16:00",
    location: "Bodhgaya Craft Center, Bihar",
    organiser: "Bal Jyoti Crafts Division",
    seatsTotal: 15,
    seatsRemaining: 6,
    image: "images/hero_bamboo_craft.jpg",
    description: "Transforming bamboo into eco-friendly products through innovation, skill development, and local craftsmanship.",
    fullDescription: "Join our master bamboo artisans in this immersive 1-day hands-on workshop. You will learn the entire journey of sustainable bamboo craftsmanship, starting from natural borax treatment to hand-splitting fibers and weaving modern home accessories. All tools and raw materials are provided by the foundation.",
    speakers: ["Manoj Manjhi (Master Craftsman)", "Priyanjali Sen (Lead Product Designer)"],
    schedule: [
      { time: "10:00 AM", activity: "Introduction & Bamboo Material Selection" },
      { time: "11:30 AM", activity: "Splitting & Slicing Fiber Demo" },
      { time: "01:00 PM", activity: "Lunch Break (Traditional Bihar Cuisine)" },
      { time: "02:00 PM", activity: "Coil and Ribbon Weaving Practice" },
      { time: "03:30 PM", activity: "Finishing & Borax Treatment overview" }
    ],
    gallery: ["images/basket_weaving_artisan.jpg", "images/hero_bamboo_craft.jpg", "images/hero_nature_weaving.jpg"]
  },
  {
    id: 2,
    title: "Handmade Rug Weaving Training",
    category: "Crafts",
    subCategories: ["Training", "Crafts"],
    status: "Upcoming",
    date: "2026-08-22",
    startTime: "09:00",
    endTime: "13:00",
    location: "Bodhgaya Weaving Shed, Bihar",
    organiser: "Master Weaver Cluster",
    seatsTotal: 10,
    seatsRemaining: 3,
    image: "images/hero_handloom_weaving.jpg",
    description: "Preserving traditional handwoven rug craftsmanship while creating sustainable livelihoods for rural artisans.",
    fullDescription: "Discover the intricate geometry and structural mathematics of dhurrie flatweaves. Our senior master weavers will guide you through spinning organic local wool, configuring wood looms, and weaving basic patterns. Ideal for textile designers and heritage lovers.",
    speakers: ["Rupa Devi (Design Coordinator)", "Satish Prasad (Weaving Superintendent)"],
    schedule: [
      { time: "09:00 AM", activity: "Warp and Weft Loom Basics" },
      { time: "10:30 AM", activity: "Color Knotting & Geometric Setup" },
      { time: "12:00 PM", activity: "Pattern Completion and Fringe Knotting" }
    ],
    gallery: ["images/rug_stack_close.jpg", "images/rugs_hanging_nature.jpg", "images/hero_luxury_rug_stack.jpg"]
  },
  {
    id: 3,
    title: "Women's Skill Development Programme",
    category: "Training",
    subCategories: ["Training", "Community"],
    status: "Upcoming",
    date: "2026-09-05",
    startTime: "11:00",
    endTime: "15:00",
    location: "Gaya Training Hub, Bihar",
    organiser: "Women Co-operative",
    seatsTotal: 30,
    seatsRemaining: 18,
    image: "images/smiling_artisan_loom.jpg",
    description: "Empowering women through tailoring, stitching, and garment production for financial independence.",
    fullDescription: "A comprehensive capacity-building camp designed to provide financial literacy, digital banking access, and industrial stitching training to rural women. Participants will receive certificates and micro-loan references for purchasing tailoring toolkits.",
    speakers: ["Sunita Devi (Co-operative Leader)", "Nisha Kumari (Livelihood Advisor)"],
    schedule: [
      { time: "11:00 AM", activity: "Opening Address & Bank Account Setups" },
      { time: "12:30 PM", activity: "Digital Financial Literacy Presentation" },
      { time: "01:30 PM", activity: "Industrial Sewing Machine Practice Session" },
      { time: "02:30 PM", activity: "Distribution of Graduation Toolkits" }
    ],
    gallery: ["images/block_printing_artisan.jpg", "images/paper_loom_weaving.jpg", "images/artisan_group_forest.jpg"]
  },
  {
    id: 4,
    title: "Eco Village Experience Tour",
    category: "Eco Tourism",
    subCategories: ["Eco Tourism"],
    status: "Upcoming",
    date: "2026-09-18",
    startTime: "08:00",
    endTime: "18:00",
    location: "Bodhgaya Eco Village, Bihar",
    organiser: "Eco-tourism Committee",
    seatsTotal: 12,
    seatsRemaining: 5,
    image: "images/hero_rural_hillside.jpg",
    description: "Promoting responsible tourism and preserving natural ecosystems in our heritage model village.",
    fullDescription: "Experience self-reliant rural lifestyles firsthand. Tour our solar micro-grids, mud-and-bamboo model cottages, organic farms, and wastewater treatment loops. Includes workshops on millet cooking and organic farming, led by village elders.",
    speakers: ["Ramesh Kumar (Eco-Village Coordinator)", "Devi Lal (Organic Farm Lead)"],
    schedule: [
      { time: "08:00 AM", activity: "Travel from Gaya & Traditional Breakfast" },
      { time: "09:30 AM", activity: "Solar Installation & Bamboo Cottages Tour" },
      { time: "11:30 AM", activity: "Organic Farm Walk & Harvesting Demo" },
      { time: "01:00 PM", activity: "Farm-to-Table Lunch" },
      { time: "03:00 PM", activity: "Clay Pottery & Basket Weaving Tryouts" }
    ],
    gallery: ["images/hero_valley_rugs.jpg", "images/rural_women_harvest.jpg", "images/hero_artisan_women.jpg"]
  },
  {
    id: 5,
    title: "Rural Entrepreneurship Workshop",
    category: "Community",
    subCategories: ["Workshops", "Community"],
    status: "Upcoming",
    date: "2026-10-02",
    startTime: "10:30",
    endTime: "17:00",
    location: "Gaya Community Hall, Bihar",
    organiser: "Livelihoods Hub",
    seatsTotal: 40,
    seatsRemaining: 24,
    image: "images/hero_artisan_exhibition.jpg",
    description: "Structured workshop covering packaging, quality control, logistics, and digital branding for rural micro-enterprises.",
    fullDescription: "A practical guide for village entrepreneurs looking to sell their crafts and agricultural products on online marketplaces. Topics cover product photography, packaging guidelines, logistics operations, and basic digital branding strategies.",
    speakers: ["Anil Sen (E-Commerce Specialist)", "Sanjay Prasad (Supply Chain Lead)"],
    schedule: [
      { time: "10:30 AM", activity: "Packaging & Quality Compliance standards" },
      { time: "12:00 PM", activity: "Online Store Setups & Photography basics" },
      { time: "02:00 PM", activity: "Logistics, Shipping partners, and payouts" },
      { time: "04:00 PM", activity: "Open Q&A & Mentorship Matchmaking" }
    ],
    gallery: ["images/hero_artisan_exhibition.jpg", "images/artisan_group_rocks.jpg", "images/community_training_circle.jpg"]
  },
  {
    id: 6,
    title: "Children's Education Camp",
    category: "Completed",
    subCategories: ["Community"],
    status: "Completed",
    date: "2026-07-15",
    startTime: "09:00",
    endTime: "12:00",
    location: "Bal Jyoti School, Bodhgaya",
    organiser: "Education Division",
    seatsTotal: 50,
    seatsRemaining: 0,
    image: "images/community_training_circle.jpg",
    description: "Quality literacy and digital learning introductory camp for child weavers and rural youth.",
    fullDescription: "Our annual child literacy camp introduced basic computer literacy, creative painting workshops, and interactive math puzzles to 50 young learners in our weaver cluster. Children received reading kits, sketching blocks, and school backpacks.",
    speakers: ["Rekha Manjhi (Primary Educator)", "Vikram Roy (Digital Literacy Volunteer)"],
    schedule: [
      { time: "09:00 AM", activity: "Interactive Storytelling Session" },
      { time: "10:00 AM", activity: "Creative Art & Sketching Workshop" },
      { time: "11:00 AM", activity: "Basic Computers & Keyboards Demo" }
    ],
    gallery: ["images/hero_community_training.jpg", "images/community_training_circle.jpg", "images/smiling_artisan_loom.jpg"]
  }
];
